### PR TITLE
Make bytes public and add String initializer

### PR DESCRIPTION
**Pull request by goloveychuk**

### CODE REVIEW

**Comment by paulofaria** [comment]
can you use the string initializer here as well, please?

https://github.com/Zewo/Data/blob/81b988e18cfcb7eeef181697b512ee214bb36d83/Source/Data.swift#L317

**Comment by paulofaria** [comment]
check if it can be used elsewhere as well

**Comment by paulofaria** [comment]
ok to merge?

**Comment by goloveychuk** [comment]
@paulofaria do you asking me? :)

**Pull request merged**
